apiVersion: v1
kind: ServiceAccount
metadata:
  name: platform-api
  namespace: workloads
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::472319730123:role/platform-api-service-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: platform-api-config
  namespace: workloads
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "create", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: platform-api-config
  namespace: workloads
subjects:
  - kind: ServiceAccount
    name: platform-api
    namespace: workloads
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: platform-api-config
