name: security-verification

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  actions: read
  contents: read
  security-events: write
  id-token: write
  attestations: write

jobs:
  codeql:
    name: CodeQL Analysis
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript
      - name: Autobuild
        uses: github/codeql-action/autobuild@v3
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

  semgrep:
    name: Semgrep Scan
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install Semgrep
        run: |
          python -m pip install --upgrade pip
          python -m pip install semgrep
      - name: Run Semgrep
        run: semgrep --config "p/ci" --sarif --output=semgrep.sarif
      - name: Upload Semgrep SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif

  dependency-security:
    name: Dependency Security
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Run npm audit
        run: npm audit --audit-level=high
      - name: Run Trivy filesystem scan
        uses: aquasecurity/trivy-action@0.20.0
        with:
          scan-type: fs
          severity: 'HIGH,CRITICAL'
          ignore-unfixed: true
          format: sarif
          output: trivy-results.sarif
      - name: Upload Trivy results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-results.sarif

  container-build:
    name: Build, SBOM, Sign and Attest
    runs-on: ubuntu-22.04
    needs:
      - dependency-security
    outputs:
      image: ${{ steps.image_ref.outputs.image_name }}:${{ github.sha }}
      image_name: ${{ steps.image_ref.outputs.image_name }}
      digest: ${{ steps.image_ref.outputs.digest }}
    env:
      IMAGE_NAME: ghcr.io/prod-ai/platform-api
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm ci
      - name: Build application
        run: npm run build
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build container image
        id: build
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ github.sha }}
          file: ./Dockerfile
      - name: Generate CycloneDX SBOM
        run: npx @cyclonedx/cyclonedx-npm --output-format json --output-file sbom.cdx.json
      - name: Upload SBOM artifact
        uses: actions/upload-artifact@v4
        with:
          name: cyclonedx-sbom
          path: sbom.cdx.json
      - name: Run Syft container SBOM
        run: |
          # Install Syft (Anchore) and generate CycloneDX SBOM for the built image
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin
          /usr/local/bin/syft ${{ env.IMAGE_NAME }}:${{ github.sha }} -o cyclonedx-json > image.cdx.json
      - name: Upload image SBOM
        uses: actions/upload-artifact@v4
        with:
          name: container-sbom
          path: image.cdx.json
      - name: Trivy image scan
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: ${{ env.IMAGE_NAME }}:${{ github.sha }}
          severity: 'HIGH,CRITICAL'
          exit-code: '1'
          ignore-unfixed: true
      - name: Cosign Sign Container
        env:
          COSIGN_EXPERIMENTAL: "1"
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
        run: |
          echo "$COSIGN_PRIVATE_KEY" > cosign.key
          cosign sign --key cosign.key --yes $IMAGE_NAME:${{ github.sha }}

      - name: Cosign Attest SBOM
        env:
          COSIGN_EXPERIMENTAL: "1"
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
        run: |
          cosign attest --predicate sbom.cdx.json --type cyclonedx --key cosign.key $IMAGE_NAME:${{ github.sha }}
      - name: Export image reference
        id: image_ref
        run: |
          echo "image_name=${IMAGE_NAME}" >> "$GITHUB_OUTPUT"
          echo "digest=${{ steps.build.outputs.digest }}" >> "$GITHUB_OUTPUT"

  generate-slsa:
    name: Generate SLSA Provenance
    needs: container-build
    permissions:
      actions: read
      id-token: write
      packages: write
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_container_slsa3.yml@v1.9.0
    with:
      image: ${{ needs.container-build.outputs.image_name }}
      digest: ${{ needs.container-build.outputs.digest }}
      registry-username: ${{ github.actor }}
    secrets:
      registry-password: ${{ secrets.GITHUB_TOKEN }}

  policy-gate:
    name: Policy Gate
    runs-on: ubuntu-22.04
    needs:
      - container-build
      - generate-slsa
    env:
      IMAGE_NAME: ghcr.io/prod-ai/platform-api
    steps:
      - uses: actions/checkout@v4
      - name: Verify Cosign signature
        env:
          COSIGN_EXPERIMENTAL: "1"
        run: cosign verify ${{ needs.container-build.outputs.image }}
      - name: Fail if attestation missing
        run: |
          cosign verify-attestation --type cyclonedx --certificate-identity-regexp ".*" --certificate-oidc-issuer https://token.actions.githubusercontent.com $IMAGE_NAME:${{ github.sha }}
